import type { NextPage } from "next";
import Head from "next/head";
import { useGetTasksQuery } from "../store/tasks";
import styled, { ThemeProvider } from "styled-components";
import { useSelector } from "react-redux";
import { RootState } from "../store/store";
import { lightTheme, darkTheme, GlobalStyles } from "../theme";

const Wrapper = styled.section``;

const Text = styled.h5`
  // color: blue;
`;

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Home: NextPage = () => {
  const { data, isLoading, isFetching, error } = useGetTasksQuery("");
  const themeMode = useSelector<RootState>((state) => state.theme.mode);

  return (
    <ThemeProvider theme={themeMode === "light" ? lightTheme : darkTheme}>
      <GlobalStyles />
      <Head>
        <title>Todo Ap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        {data &&
          data.map((task) => (
            <Wrapper key={task.id}>
              <Text>{task.task_content}</Text>
            </Wrapper>
          ))}
        {isLoading && "Loading"}
      </Main>
    </ThemeProvider>
  );
};

export default Home;
